### ISSUE TITLE
example - memoryll.py errors with python3

### ISSUE THREAD

**Issue by everygamer** [fusepy/fusepy#108]
Hi, sorry, wasn't sure if this is how you wanted us to submit issues when we find one. I was looking at fusepy for a college project and noticed that the memoryll.py example errors when using python3.

Python3 Command:
python3 /test/examples/memoryll.py /mount/path

Error:
```
Traceback (most recent call last):
  File "memoryll.py", line 162, in <module>
    fuse = Memory(args.mount)
  File "/test/fusepy/examples/fusell.py", line 489, in __init__
    argv = fuse_args(len(args), (ctypes.c_char_p * len(args))(*args),0)
TypeError: bytes or integer address expected instead of str instance
```

With python 2.7 it appears to work fine when I use this command ...
python /test/examples/memoryll.py /mount/path

I had to copy the fusell.py file into the examples folder to run it too, kept saying it couldn't find the fusell module, but guessing that is because I didn't have it in my env path.

Looks like libfuse 2.9.4 is installed on my system and python 3.5.2

**Comment by CJStadler** [comment]
I think this should be fixed by https://github.com/fusepy/fusepy/pull/106?

**Comment by eestrada** [comment]
@CJStadler I literally merged PR #106 a minute ago. Feel free to try out the latest version of the library from the `master` branch to see if it fixes your issue. If so, we can close this issue.

**Comment by eestrada** [comment]
😅 Sorry, I addressed that last comment to the wrong person. @everygamer, same thing I said to @CJStadler, but directed at you instead. 😅

**Comment by everygamer** [comment]
That did the trick, thank you!
