### ISSUE TITLE
Can I pass options such as `FUSE_BIG_WRITES`?

### ISSUE THREAD

**Issue by KonstantinSchubert** [fusepy/fusepy#121]
First off, if this is not the right place to ask, I will be happy to re-post my question in the right place.

I would like to try and improve the performance of my file system by allowing bigger writes.
Fuse has the `FUSE_BIG_WRITES` option https://github.com/torvalds/linux/blob/d7afaec0b564f0609e116f562983b8e72fc3e9c9/include/uapi/linux/fuse.h#L221

Can I somehow use this option with fusepy?

**Comment by diman82** [comment]
@KonstantinSchubert No problem passing this option: `big_writes=True`
