### ISSUE TITLE
How to get fullpath?

### ISSUE THREAD

**Issue by diman82** [fusepy/fusepy#131]
I get only a relative path (in getattr & write operations 'path' argument), so when I try to copy file NOT FROM the myfuse.py run directory, I get runtime errors..
How can I pass a fullpath argument, so that proper file copy can be held?

**Comment by paulo-raca** [comment]
The paths are relative to your filesystem only, and your code doesn't need to worry with anything outside of it.

If it needs to copy files between different filesystems, the OS will read contents from files in one filesystem and write to files in the other filesystem -- your code cannot distinguish it from other read/write operations.

**Comment by diman82** [comment]
@paulo-raca Thanks, it was my bad - I was using fullpath for os.stats(fullpath) - it needs absolute path of file.
BTW, is there any way to get the file stats from data param? Couldn't find any other way to get them..
