### ISSUE TITLE
Can't use fuse while running in docker

### ISSUE THREAD

**Issue by nadavaviv** [fusepy/fusepy#137]
I'm trying to run a fuse module written in fusepy while using an ubuntu 18.04 image.
When working on a regular host (mac os) it works just fine.

When trying to run the code over a container, I get the following error:
`fuse: device not found, try 'modprobe fuse' first`

Thinking this was a problem with my code I tried running the example code given in:
https://thepythoncorner.com/dev/writing-a-fuse-filesystem-in-python/
but had the same results...

While searching for a solution, I found some people suggesting to run the container with the following command:
`docker run -d --rm \
           --device /dev/fuse \
           --cap-add SYS_ADMIN \
      <image_id/name>`

But unfortunately, it didn't work, and even if it does, for security reasons, I can't use this in production.

Is there any way to work around this?

Thanks

**Comment by N-Coder** [comment]
This is an issue of Docker (in combination with fuse), not an issue of fusepy. You'll have to wait for the Docker devs to fix this, then fuse and fusepy should work without further ado:
https://github.com/docker/for-linux/issues/321
