### ISSUE TITLE
No way to suppress call to signal.signal

### ISSUE THREAD

**Issue by timdawborn** [fusepy/fusepy#14]
In Python, you can only call `signal.signal` from the main thread.

http://docs.python.org/2.7/library/signal.html#signal.signal
http://docs.python.org/3/library/signal.html#signal.signal

Attempting to do so in a non-main thread causes `ValueError` to be raised. Attempting to invoke `FUSE` from the non-main thread thus dies, as there's no way to suppress the call to `signal.signal` in `FUSE.__init__`.

https://github.com/terencehonles/fusepy/blob/master/fuse.py#L390

Is there a reason why adding a keyword argument to the `FUSE` constructor to suppress this call to `signal.signal` would be bad?

**Comment by eestrada** [comment]
It seems this has been resolved by @terencehonles in commit 27d76e442d96139f9038d83d23275877fa3d3c9b. Closing as fixed.
