### ISSUE TITLE
read() operations cause zero-filled files of 'size' to be written on errors

### ISSUE THREAD

**Issue by aryounce** [fusepy/fusepy#15]
As part of a test I'm doing (on Mac OS 10.8) I decided to cause every read() to fail with errno.EPERM. The Finder is displaying the appropriate error when I try to copy a file out of the FUSE drive, but the operation still returns a zero-filled byte array. As a result a zero-filled file corresponding to the 'size' of the read is created.

Is this fusepy or FUSE driver related? A cursory reading of the fusepy module seems to pin this particular issue on the underlying FUSE driver implementation. Thoughts?

**Edit**

After more reading the point in the fusepy code that seems most related to the issue is the [_wrapper() static method](https://github.com/terencehonles/fusepy/blob/master/fuse.py#L416). My understanding of the [FUSE operations](http://fuse.sourceforge.net/doxygen/structfuse__operations.html) is that all errors (destined for errno) are returned as negative values of the errno in question.

I'm not currently clear on how this affects [read()](http://fuse.sourceforge.net/doxygen/structfuse__operations.html#a2a1c6b4ce1845de56863f8b7939501b5) as 0 and -1 are significant return values in the cases of EOF or error.

**Comment by eestrada** [comment]
@aryounce Is this still an issue?

**Comment by terencehonles** [comment]
I'm not 100% sure of the use case, but patching the example memory.py with the following

```diff
diff --git a/examples/memory.py b/examples/memory.py
index b0e7907..3aab43b 100755
--- a/examples/memory.py
+++ b/examples/memory.py
@@ -4,7 +4,7 @@ from __future__ import print_function, absolute_import, division
 import logging
 
 from collections import defaultdict
-from errno import ENOENT
+from errno import ENOENT, EPERM
 from stat import S_IFDIR, S_IFLNK, S_IFREG
 from time import time
 
@@ -80,11 +80,10 @@ class Memory(LoggingMixIn, Operations):
         self.files['/']['st_nlink'] += 1
 
     def open(self, path, flags):
-        self.fd += 1
-        return self.fd
+        raise OSError(EPERM, 'Test operation not permitted')
 
     def read(self, path, size, offset, fh):
-        return self.data[path][offset:offset + size]
+        raise OSError(EPERM, 'Test operation not permitted')
 
     def readdir(self, path, fh):
         return ['.', '..'] + [x[1:] for x in self.files if x != '/']
```
running `echo hi > test; cat test` I got the following:

```
DEBUG:fuse.log-mixin:-> open /test (32768,)
DEBUG:fuse.log-mixin:<- open '[Errno 13] Test operation not permitted'
^CDEBUG:fuse.log-mixin:-> destroy / ()
DEBUG:fuse.log-mixin:<- destroy None
```

and removing the open definition:

```
DEBUG:fuse.log-mixin:-> open /test (32768,)
DEBUG:fuse.log-mixin:<- open 2
DEBUG:fuse.log-mixin:-> read /test (4096L, 0, 2L)
DEBUG:fuse.log-mixin:<- read '[Errno 13] Test operation not permitted'
DEBUG:fuse.log-mixin:-> read /test (4096L, 0, 2L)
DEBUG:fuse.log-mixin:<- read '[Errno 13] Test operation not permitted'
DEBUG:fuse.log-mixin:-> flush /test (2L,)
DEBUG:fuse.log-mixin:<- flush 0
DEBUG:fuse.log-mixin:-> release /test (2L,)
DEBUG:fuse.log-mixin:<- release 0
```

I think that is working as intended(?)
