### ISSUE TITLE
IOCTL and fusepy

### ISSUE THREAD

**Issue by hasanatkazmi** [fusepy/fusepy#18]
Fuse 2.6 has ioctl integration. Should we expect fusepy to support ioctl anytime sooner?

**Comment by emanuelef** [comment]
Hi, I'm interested in having ioctl supported ? Is it going to happen ?
Thanks

**Comment by terencehonles** [comment]
If you have time to write a pull request it would be appreciated. Otherwise this is currently not on the roadmap

**Comment by hetii** [comment]
Yep would be grate to have it :) 
I try add it but so far no luck :/

**Comment by steinbeck65** [comment]
I've submitted a pull request (#62) to add IOCTL support, if you want to give it a try or comment.

**Comment by arekbulski** [comment]
I second this motion. Could use a full ioctl where structured data can be sent to fs or received from it.

**Comment by eestrada** [comment]
I am currently reviewing @steinbeck65's PR #62 for inclusion. This should be a initial step in the direction of getting IOCTL support.

**Comment by terencehonles** [comment]
It looks close @steinbeck65 thanks for your contributions 🙂

**Comment by eestrada** [comment]
It seems this has been addressed by PR #62. Will close this now.

Thanks again @steinbeck65!
