### ISSUE TITLE
Exit from inside, without fusermount 

### ISSUE THREAD

**Issue by joe42** [fusepy/fusepy#21]
Hi!

I don't know if this is possible, but can you exit the filesystem from inside the program?
I tried with sys.exit, but it just raises an Exception instead of shutting down the program: 

```
File "cloudfusion/fuse.py", line 301, in _wrapper_
    return func(*args, **kwargs) or 0
  File "cloudfusion/fuse.py", line 324, in unlink
    return self.operations('unlink', path)
  File "cloudfusion/fuse.py", line 507, in __call__
    return getattr(self, op)(*args)
  File "cloudfusion/pyfusebox/configurable_pyfusebox.py", line 118, in unlink
    exit(0)
  File "/usr/lib/python2.6/site.py", line 337, in __call__
    raise SystemExit(code)
SystemExit: 0
```

**Comment by eestrada** [comment]
If you are using multi-threading in python and your threads are not marked as daemonic threads, they will cause your application to hang until they complete their work (which may be indefinitely). Either mark the threads as daemonic or, if they need to do some clean up, have a variable somewhere that all the threads can access to check if they should clean up and return.

**Comment by earonesty** [comment]
A programmatic way of exiting the main loop, that doesn't relay on signal handling would be helpful.   if the main FUSE function returned a socket, for example, that could be used to tell it to quit, then threading wouldn't be an issue.

**Comment by eestrada** [comment]
I am interested to hear who else is having this issue/situation and wants a solution related to this. @earonesty, you suggest an interesting solution; something like that may be a good way forward if it seems there is enough demand for it.

**Comment by itdaniher** [comment]
@eestrada I've run into this - I use fusepy for a souped up virtualenv, and as such, killing the env gracefully after the target script has exited is a desired feature. Not sure about implementing with a socket, maybe with a signal handler?

**Comment by eestrada** [comment]
@itdaniher I think you are right that using signals caught by a signal handler is the probably the best way to do this. I'll need to think for a while about what the best way to integrate this into the current codebase would be.

I think some of @joe42's other issues (i.e. not being able to kill the program from within itself) most likely relate to what I mentioned in my [earliest comment](https://github.com/fusepy/fusepy/issues/21#issuecomment-196664323) about properly marking dealing with threads at shutdown.

**Comment by N-Coder** [comment]
With #103 being merged, this can probably be closed.

**Comment by eestrada** [comment]
Thanks for the reminder @N-Coder. Just so that we don't forget, I have added an issue (#109) to remind us to create test cases for this once the testing framework is bootstrapped.
