### ISSUE TITLE
Py3: FUSE.listxattr throws TypeError

### ISSUE THREAD

**Issue by kernowcastellan** [fusepy/fusepy#24]
Under python3.3, I get a TypeError thrown on listxattr:

```
Traceback (most recent call last):
  File "/home/kernow/proj/fuse.py", line 420, in _wrapper
    return func(*args, **kwargs) or 0
  File "/home/kernow/proj/fuse.py", line 580, in listxattr
    ret = '\x00'.join(attrs).encode(self.encoding) + '\x00'
TypeError: can't concat bytes to str
```

I think the problem is in:

``` python
 def listxattr(self, path, namebuf, size):
        attrs = self.operations('listxattr', path.decode(self.encoding)) or ''
        ret = '\x00'.join(attrs).encode(self.encoding) + '\x00'
```

The `attrs` returned from the operation are unicode, and so the first `'\x00'` is rightly also unicode, and then the joined string is `encode`d into bytes.

The second `'\x00'` should then be explicitly bytes - `b'\x00'`. Of course, the byes literal only works in v3, so you would probably need `'\x00'.encode('ascii')`

**Comment by tomsmeding** [comment]
Still the case now; this fix works here (mac osx 10.11)
