### ISSUE TITLE
Input/output error when getattr() called

### ISSUE THREAD

**Issue by ly0** [fusepy/fusepy#29]
when I entered my mount point,

getattr() returned the following dict:

> {'st_ctime': 1393850496, 'st_nlink': 2, 'bd_blocklist': 0, 'st_gid': 0, 'st_dev': 0, 'st_ino': 0, 'st_mode': 16895, 'st_mtime': 1393850496, 'bd_md5': 0, 'st_size': 0, 'st_uid': 0, 'bd_fsid': 0, 'st_atime': 0}

(st_mode is stat.S_IFDIR | 0777)
then 

```
root@Hiwifi:/tmp/baidu-fuse# cd mnt
-bash: cd: mnt: Input/output error
```

Does anyone could tell me what's wrong with this? 
sorry for my English.

**Comment by eestrada** [comment]
Hi @ly0, are you still having this problem? If so, can you give more information? Is this using one of the `fusepy` example files, or is this in your own code that uses `fusepy`?

**Comment by ly0** [comment]
emmmmm, a message traveled the universe 👍

**Comment by eestrada** [comment]
I'll take your thumbs up to mean that this is no longer a problem. I'll close the issue now.
