### ISSUE TITLE
inotify integration

### ISSUE THREAD

**Issue by joe42** [fusepy/fusepy#5]
Hi,

First off, thanks for writing and maintaining fusepy. And a late welcome to GitHub :)
I successfully use fusepy for connecting to file hosters like Dropbox and Sugarsync,
as well as for a manga reader.
Do you happen to know of a way to use inotify on a fusepy file system or a similar solution?
It would be nice to get notifications of file changes without cyclic polling.

Thanks a lot!

**Comment by eestrada** [comment]
I think this has been answered, more or less by @terencehonles. @joe42, if you feel this question deserves more consideration, please comment and we can reopen it to continue the conversation.
