### ISSUE TITLE
listxattr appears to not work...

### ISSUE THREAD

**Issue by cloudtoad** [fusepy/fusepy#52]
From the CLI, when I type the following, nothing appears (next line is sh prompt):

`getfattr -d bar`

Debugging shows these two lines:

```
DEBUG:fuse.log-mixin:-> listxattr /bar ()
DEBUG:fuse.log-mixin:<- listxattr ['table-name', 'master', 'file-type', 'no-db-update', 'primary-keys']
```

Getting a single attribute works fine:

```
vagrant@ubuntu:~/projects/kangaroo/test$ getfattr -n file-type bar
# file: bar
file-type="regular"
```

Running on Ubuntu 16.04 / Python 2.7.11

**Comment by terencehonles** [comment]
I believe this was fixed in c95ca3913eccf360207bbfc69bd52a91fc77197f I just tested both Python 2 & 3 and am able to use the following test:

```
$ echo test > test
$ xattr -w user.comment test test
$ xattr -l test
user.comment: test
```

Maybe this was before the change was pushed to pypi?
