### ISSUE TITLE
memoryfs: how to support multiple directory levels

### ISSUE THREAD

**Issue by nonbeing** [fusepy/fusepy#65]
Thanks for fusepy - it's probably the best Python binding to FUSE available. 

`fusepy/examples/memory.py` has this comment:
> 'Example memory filesystem. Supports only one level of files.'

and indeed this is the case.

How could I support a proper memoryfs (i.e. one that works for multiple levels of directories)?  Could you please share some hints? Please point me in the right direction?

**Comment by itdaniher** [comment]
https://github.com/bazaar-projects/kungfuse does what you need

**Comment by terencehonles** [comment]
I'm going to close this as use kungfuse, but we can continue in #78
