### ISSUE TITLE
only call ctypes.utils.find_library if basic searches fail?

### ISSUE THREAD

**Issue by itdaniher** [fusepy/fusepy#77]
Ran into this issue (and fixed it) in pyrtlsdr - as it happens, find_library is a true heavyweight function, invoking (on Linux) a bunch of build tools in an attempt to find the path to the shared object. On most Linux distros, a search of `LD_LIBRARY_PATH` (if present), followed by globbing `/lib/*`, `/usr/lib/*`, and `/usr/local/lib/*` would suffice. If these cheap glob matches fail, then `find_library` can be invoked as a last ditch effort.

See also - https://github.com/roger-/pyrtlsdr/pull/75

**Comment by itdaniher** [comment]
this is actually a duplicate of PR https://github.com/fusepy/fusepy/pull/31

**Comment by eestrada** [comment]
@itdaniher Those locations, although common, are unlikely to be
universal across all Unix-like operating systems.

> this is actually a duplicate of PR #31

I like the approach from PR #31; if the user wants to optimize loading
speed or needs to load from a non-standard place, they have all that
flexibility thru setting the environment variables.

Are there some benefits to the approach you suggest in this issue that
I may be missing?

**Comment by itdaniher** [comment]
Setting an environment variable with the abspath is fine. It reduces the implementation complexity vs adding LD_LIBRARY_PATH walking or a significant number of globs.

That said, checking /usr/lib/libfuse* and /lib/*/libfuse* covers (every Linux I could find) including [Fedora](https://rpmfind.net/linux/RPM/fedora/devel/rawhide/armhfp/f/fuse-libs-2.9.7-10.fc28.armv7hl.html), [Debian](https://packages.debian.org/sid/amd64/libfuse2/filelist),  [Alpine](https://pkgs.alpinelinux.org/contents?branch=edge&name=fuse2-dev&arch=x86&repo=testing),  [Arch](https://www.archlinux.org/packages/extra/x86_64/fuse2/), so I don't expect that globs would fail ```if sys.platform == "linux"```

**Comment by eestrada** [comment]
> ...checking /usr/lib/libfuse* and /lib//libfuse covers (every Linux I could find) including Fedora, Debian, Alpine, Arch, so I don't expect that globs would fail if sys.platform == "linux"

It makes sense that these paths cover all major Linuxes. However, in
theory a Unix-y OS can place libraries anywhere in the file hierarchy
(macOS is a good example of this). Hard coding paths into `fusepy`
makes for special cases that need to be maintained moving forward.

> Setting an environment variable with the abspath is fine. It reduces the implementation complexity vs adding LD_LIBRARY_PATH walking or a significant number of globs.

I fully agree that this approach reduces the code complexity. It is
cleaner to offload the responsibility to the user via the environment
variable. At the end of the day, `fusepy` doesn't (and shouldn't) care
where the `libfuse.so` library lives, so long as it can find it: it is
the user's or the system's responsibility to tell `fusepy` where to
look. Based on this perspective, the logic becomes pretty clear to me
at this point:

1. Check for the presence of an environment variable pointing to where
the library lives
2. If that isn't present, fallback to calling `find_library`

I'm working on an implementation of this. It will be something in
between PR #31 and PR #51 (but attempting to load the envar first, as
per PR #31).

**Comment by terencehonles** [comment]
Well I guess I missed the discussion here 🤐 but I implemented this with 4a2cb07339b6d812eb174445c8f9c28238f00343 and closed the issues #31 and #51 

Thanks for your thoughtful input @eestrada
