### ISSUE TITLE
Wont install from pipi becasue README file is missing

### ISSUE THREAD

**Issue by guysoft** [fusepy/fusepy#8]
I get the following output:

$ ~/pythonenv/bin/easy_install fusepy
Searching for fusepy
Reading http://pypi.python.org/simple/fusepy/
Reading http://code.google.com/p/fusepy/
Reading http://github.com/terencehonles/fusepy
Best match: fusepy 2.0.1
Downloading http://pypi.python.org/packages/source/f/fusepy/fusepy-2.0.1.tar.gz#md5=00e8b212bc8cd4fdaa012a0a5f5ba9f4
Processing fusepy-2.0.1.tar.gz
Running fusepy-2.0.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-SAq4jc/fusepy-2.0.1/egg-dist-tmp-N5EARj
error: README: No such file or directory

Any idea why this is happening? I see there is a README file

**Comment by eestrada** [comment]
Users should almost universally be using `pip` and the repo now has a `README` so even if someone is using `easy_install`, this should work. Closing this issue now.
