### ISSUE TITLE
`fuse_file_info` doesn't have `nonseekable`

### ISSUE THREAD

**Issue by paulo-raca** [fusepy/fusepy#83]
I have a socket-like file that can be read, but not seeked.

On the C api, I can use `fi.nonseekable = 1` to indicate that, but this doesn't seem to be present on fusepy.

Is that an error, or is there something I am missing?

**Comment by paulo-raca** [comment]
(I noticed a few other mismatches which I don't really care right now, e.g., `getattr` has an extra `fuse_file_info*` argument for `fgetattr`)

**Comment by terencehonles** [comment]
It's likely this is not implemented, but I didn't have a chance to review that statement. If you would like to contribute a patch it would be appreciated.
